version: '2'
services:
  web:
    extends:
      file: docker-compose.base.yml
      service: web
    environment:
      DEBUG: app*,-express*
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
